Use adb wait-for-device for boot status check
bitrise-steplib/steps-wait-for-android-emulator pull request #25
Opened 2021-12-06 16:02 UTC by godrei

### Checklist

- [x] I've read and followed the [Contribution Guidelines](https://github.com/bitrise-steplib/.github/blob/main/CONTRIBUTING.md)
- [x] `step.yml` and `README.md` is updated with the changes (if needed)

### Version

Requires a *MAJOR/MINOR/PATCH* [version update](https://semver.org/)

### Context

- Use `wait-for-device` adb command for emulator boot status check

```
adb help

 wait-for[-TRANSPORT]-STATE...
     wait for device to be in a given state
     STATE: device, recovery, rescue, sideload, bootloader, or disconnect
     TRANSPORT: usb, local, or any [default=any]
```

`adb wait-for-device` resolves issues like: `device offline`, as it only executes the given command if the emulator is in the desired `device` state.

- Updated boot status check command timeout from 20s to 1m.
- Only using `getprop sys.boot_completed` for boot complete check.
- Improve emulator unlock
- Ensure adb server is running prior to other adb calls

### Changes

- update `go-utils`, `go-steputils` and `go-android` dependencies

### Investigation details

### Decisions

2021-12-07 08:28 UTC, ofalvai commented
@godrei if it's not too much hassle, can you please update go-steputils in this PR? 🥺 I want [this feature](https://github.com/bitrise-io/go-steputils/pull/42) to land in as many steps as possible.

2021-12-14 09:59 UTC, godrei commented
@ofalvai updated in https://github.com/bitrise-steplib/steps-wait-for-android-emulator/pull/25/commits/b40696f124893cee5f0976c030e33444149c40c5

2021-12-14 11:43 UTC, ofalvai commented on e2e/bitrise.yml
> +    - git::https://github.com/bitrise-steplib/steps-avd-manager@MOB-268-hanging-sdkmanager:
Should we merge that to master?

2021-12-14 12:22 UTC, ofalvai approved these changes

2021-12-14 13:23 UTC, mateherber requested changes

2021-12-14 13:51 UTC, godrei commented on commands.go
> +			log.TPrintf("Failed with output: %s, error: %s", strings.TrimSpace(output.String()), err)
updated in https://github.com/bitrise-steplib/steps-wait-for-android-emulator/pull/25/commits/c6dc3149fe813c7ebfee62dd46fb447b98872fed

2021-12-14 22:16 UTC, mateherber submitted a review, later dismissed

2022-08-09 09:57 UTC, closed without merging

2022-08-19 19:01 UTC, DamienBitrise commented
Any reason why this was never released?

2022-08-29 09:00 UTC, godrei commented
@DamienBitrise more recent PR related to this was merged: https://github.com/bitrise-steplib/steps-wait-for-android-emulator/pull/28